name: HuskHomesGUI
main: net.william278.huskhomes.gui.HuskHomesGui
version: '${version}'
description: '${description}'
api-version: 1.17
depend: [ 'HuskHomes' ]
folia-supported: true
authors: ['William278', 'Obydux']
website: 'https://github.com/Obydux'

commands:
  huskhomesgui:
    description: 'View HuskHomesGUI plugin information & reload configs'
    usage: '/<command> <reload/about>'
    permission: 'huskhomesgui.command'

permissions:
  huskhomesgui.command:
    description: 'Allows access to the /huskhomesgui command'
    default: op